In [4]:
import pandas as pd
import os

In [2]:
file_dir = "/lustre/groups/ml01/workspace/ot_perturbation/models/otfm/pbmc_new_cytokine_stochastic_metrics"

In [10]:
dfs = []
for f in os.listdir(file_dir):
    if "df_calibration" in f:
        continue
    df = pd.read_csv(os.path.join(file_dir, f), index_col=0)
    df["reg"] = f.split("_")[-1].strip(".csv")
    dfs.append(df) 

df = pd.concat(dfs, axis=0)

In [13]:
df_stoch = df[df["reg"]=="0.1"]

In [14]:
df_cf = pd.read_csv("/lustre/groups/ml01/workspace/ot_perturbation/data/pbmc/metrics/metrics_new_cytokine.csv")

In [35]:
df_stoch.head()

,ood_e_distance_0,decoded_ood_r_squared_0,ood_e_distance_1,decoded_ood_r_squared_1,ood_e_distance_2,decoded_ood_r_squared_2,ood_e_distance_3,decoded_ood_r_squared_3,ood_e_distance_4,decoded_ood_r_squared_4,...,var_mean_deg_gex_Treg,mean_var_mean_gex_per_cell_type,mean_var_mean_deg_gex_per_cell_type,frechet_variance_NKT,var_mean_gex_NKT,var_mean_deg_gex_NKT,frechet_variance_pDC,var_mean_gex_pDC,var_mean_deg_gex_pDC,reg
Donor10_4-1BBL,2.349463,0.986396,2.285095,0.986557,3.130922,0.985566,3.108891,0.985691,3.053297,0.985754,...,0.002288,0.000102,0.000945,NaN,NaN,NaN,NaN,NaN,NaN,0.1
Donor11_4-1BBL,4.565771,0.970447,5.383643,0.968852,6.516719,0.966302,6.403669,0.966762,6.348230,0.966842,...,0.000127,0.000076,0.000773,0.127738,0.000053,0.000455,NaN,NaN,NaN,0.1
Donor12_4-1BBL,5.649290,0.969592,5.130601,0.971112,4.438625,0.972942,4.228786,0.973664,4.361504,0.973219,...,0.002224,0.000091,0.000939,0.804987,0.000131,0.001493,NaN,NaN,NaN,0.1
Donor1_4-1BBL,8.138366,0.978341,7.704112,0.979168,6.147884,0.981492,6.005706,0.981848,5.908851,0.981989,...,0.002446,0.000373,0.003341,262.812716,0.001814,0.016246,64.762333,0.000772,0.00371,0.1
Donor2_4-1BBL,2.840085,0.983519,2.926538,0.983404,2.930364,0.983364,2.774895,0.983875,2.654739,0.984078,...,0.002167,0.000114,0.000997,5.098595,0.000294,0.002698,NaN,NaN,NaN,0.1

In [37]:
df_stoch["donor_cytokine"] = df_stoch.index
df_stoch["donor"] = df_stoch.apply(lambda x: x["donor_cytokine"].split("_")[0], axis=1)
df_stoch["cytokine"] = df_stoch.apply(lambda x: x["donor_cytokine"].split("_")[1], axis=1)

In [38]:
df_stoch["donor"].value_counts()

donor
Donor10    11
Donor11    11
Donor12    11
Donor1     11
Donor2     11
Donor3     11
Donor4     11
Donor5     11
Donor6     11
Donor7     11
Donor8     11
Donor9     11
Name: count, dtype: int64

In [39]:
df_stoch["cytokine"].value_counts()

cytokine
4-1BBL         12
IFN-epsilon    12
IL-15          12
OX40L          12
Noggin         12
APRIL          12
OSM            12
ADSF           12
BAFF           12
IFN-beta       12
C5a            12
Name: count, dtype: int64

In [17]:
df_stoch.shape

(132, 76)

In [18]:
df_cf.head()

,Unnamed: 0,mean_decoded_r_sq_per_cell_type,mean_e_distance_per_cell_type,mean_mmd_per_cell_type,mean_sdiv_10_per_cell_type,mean_sdiv_100_per_cell_type,mean_deg_r_sq_per_cell_type,mean_deg_e_distance_per_cell_type,mean_deg_mmd_per_cell_type,mean_deg_sdiv_10_per_cell_type,...,div_10_pDC,div_100_pDC,deg_decoded_r_squared_pDC,deg_e_distance_pDC,deg_mmd_pDC,deg_div_10_pDC,deg_div_100_pDC,donor_cytokine,donor,cytokine
0,Donor4_C5a,0.955791,11.660839,0.008871,90.671855,12.128944,0.873296,17.662023,0.040608,125.486287,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Donor4_C5a,Donor4,C5a
1,Donor7_OX40L,0.922924,35.460599,0.013862,111.972876,25.847652,0.765109,35.802167,0.046710,147.587429,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Donor7_OX40L,Donor7,OX40L
2,Donor10_C5a,0.948272,16.919249,0.010235,97.359693,15.502340,0.816124,25.159851,0.041936,139.200932,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Donor10_C5a,Donor10,C5a
3,Donor11_4-1BBL,0.931346,22.054480,0.014290,102.952084,17.665734,0.813616,24.228663,0.046342,151.745742,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Donor11_4-1BBL,Donor11,4-1BBL
4,Donor6_OSM,0.955859,13.854135,0.007579,96.074269,13.403070,0.880971,18.501366,0.038873,129.942240,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Donor6_OSM,Donor6,OSM

In [20]:
list(df_cf.columns)

['Unnamed: 0',
 'mean_decoded_r_sq_per_cell_type',
 'mean_e_distance_per_cell_type',
 'mean_mmd_per_cell_type',
 'mean_sdiv_10_per_cell_type',
 'mean_sdiv_100_per_cell_type',
 'mean_deg_r_sq_per_cell_type',
 'mean_deg_e_distance_per_cell_type',
 'mean_deg_mmd_per_cell_type',
 'mean_deg_sdiv_10_per_cell_type',
 'mean_deg_sdiv_100_per_cell_type',
 'decoded_r_squared_B Naive',
 'decoded_r_squared_CD4 Memory',
 'decoded_r_squared_CD14 Mono',
 'decoded_r_squared_CD16 Mono',
 'decoded_r_squared_CD8 Memory',
 'decoded_r_squared_CD56-bright NK',
 'decoded_r_squared_CD4 Naive',
 'decoded_r_squared_CD8 Naive',
 'decoded_r_squared_B Intermediate/Memory',
 'decoded_r_squared_CD56-dim NK',
 'decoded_r_squared_cDC',
 'e_distance_B Naive',
 'e_distance_CD4 Memory',
 'e_distance_CD14 Mono',
 'e_distance_CD16 Mono',
 'e_distance_CD8 Memory',
 'e_distance_CD56-bright NK',
 'e_distance_CD4 Naive',
 'e_distance_CD8 Naive',
 'e_distance_B Intermediate/Memory',
 'e_distance_CD56-dim NK',
 'e_distance_cDC',
 'mmd_B Naive',
 'mmd_CD4 Memory',
 'mmd_CD14 Mono',
 'mmd_CD16 Mono',
 'mmd_CD8 Memory',
 'mmd_CD56-bright NK',
 'mmd_CD4 Naive',
 'mmd_CD8 Naive',
 'mmd_B Intermediate/Memory',
 'mmd_CD56-dim NK',
 'mmd_cDC',
 'div_10_B Naive',
 'div_10_CD4 Memory',
 'div_10_CD14 Mono',
 'div_10_CD16 Mono',
 'div_10_CD8 Memory',
 'div_10_CD56-bright NK',
 'div_10_CD4 Naive',
 'div_10_CD8 Naive',
 'div_10_B Intermediate/Memory',
 'div_10_CD56-dim NK',
 'div_10_cDC',
 'div_100_B Naive',
 'div_100_CD4 Memory',
 'div_100_CD14 Mono',
 'div_100_CD16 Mono',
 'div_100_CD8 Memory',
 'div_100_CD56-bright NK',
 'div_100_CD4 Naive',
 'div_100_CD8 Naive',
 'div_100_B Intermediate/Memory',
 'div_100_CD56-dim NK',
 'div_100_cDC',
 'deg_decoded_r_squared_B Naive',
 'deg_decoded_r_squared_CD4 Memory',
 'deg_decoded_r_squared_CD14 Mono',
 'deg_decoded_r_squared_CD16 Mono',
 'deg_decoded_r_squared_CD8 Memory',
 'deg_decoded_r_squared_CD56-bright NK',
 'deg_decoded_r_squared_CD4 Naive',
 'deg_decoded_r_squared_CD8 Naive',
 'deg_decoded_r_squared_B Intermediate/Memory',
 'deg_decoded_r_squared_CD56-dim NK',
 'deg_decoded_r_squared_cDC',
 'deg_e_distance_B Naive',
 'deg_e_distance_CD4 Memory',
 'deg_e_distance_CD14 Mono',
 'deg_e_distance_CD16 Mono',
 'deg_e_distance_CD8 Memory',
 'deg_e_distance_CD56-bright NK',
 'deg_e_distance_CD4 Naive',
 'deg_e_distance_CD8 Naive',
 'deg_e_distance_B Intermediate/Memory',
 'deg_e_distance_CD56-dim NK',
 'deg_e_distance_cDC',
 'deg_mmd_B Naive',
 'deg_mmd_CD4 Memory',
 'deg_mmd_CD14 Mono',
 'deg_mmd_CD16 Mono',
 'deg_mmd_CD8 Memory',
 'deg_mmd_CD56-bright NK',
 'deg_mmd_CD4 Naive',
 'deg_mmd_CD8 Naive',
 'deg_mmd_B Intermediate/Memory',
 'deg_mmd_CD56-dim NK',
 'deg_mmd_cDC',
 'deg_div_10_B Naive',
 'deg_div_10_CD4 Memory',
 'deg_div_10_CD14 Mono',
 'deg_div_10_CD16 Mono',
 'deg_div_10_CD8 Memory',
 'deg_div_10_CD56-bright NK',
 'deg_div_10_CD4 Naive',
 'deg_div_10_CD8 Naive',
 'deg_div_10_B Intermediate/Memory',
 'deg_div_10_CD56-dim NK',
 'deg_div_10_cDC',
 'deg_div_100_B Naive',
 'deg_div_100_CD4 Memory',
 'deg_div_100_CD14 Mono',
 'deg_div_100_CD16 Mono',
 'deg_div_100_CD8 Memory',
 'deg_div_100_CD56-bright NK',
 'deg_div_100_CD4 Naive',
 'deg_div_100_CD8 Naive',
 'deg_div_100_B Intermediate/Memory',
 'deg_div_100_CD56-dim NK',
 'deg_div_100_cDC',
 'decoded_ood_r_squared',
 'ood_e_distance',
 'ood_mmd',
 'ood_sdiv_10',
 'ood_sdiv_100',
 'predicted_deg_genes',
 'wandb_name',
 'donors_in_train',
 'num_donors_in_train',
 'decoded_r_squared_Treg',
 'decoded_r_squared_NKT',
 'decoded_r_squared_MAIT',
 'e_distance_Treg',
 'e_distance_NKT',
 'e_distance_MAIT',
 'mmd_Treg',
 'mmd_NKT',
 'mmd_MAIT',
 'div_10_Treg',
 'div_10_NKT',
 'div_10_MAIT',
 'div_100_Treg',
 'div_100_NKT',
 'div_100_MAIT',
 'deg_decoded_r_squared_Treg',
 'deg_decoded_r_squared_NKT',
 'deg_decoded_r_squared_MAIT',
 'deg_e_distance_Treg',
 'deg_e_distance_NKT',
 'deg_e_distance_MAIT',
 'deg_mmd_Treg',
 'deg_mmd_NKT',
 'deg_mmd_MAIT',
 'deg_div_10_Treg',
 'deg_div_10_NKT',
 'deg_div_10_MAIT',
 'deg_div_100_Treg',
 'deg_div_100_NKT',
 'deg_div_100_MAIT',
 'decoded_r_squared_pDC',
 'e_distance_pDC',
 'mmd_pDC',
 'div_10_pDC',
 'div_100_pDC',
 'deg_decoded_r_squared_pDC',
 'deg_e_distance_pDC',
 'deg_mmd_pDC',
 'deg_div_10_pDC',
 'deg_div_100_pDC',
 'donor_cytokine',
 'donor',
 'cytokine']

In [21]:
data_dir = "/lustre/groups/ml01/workspace/ot_perturbation/data/pbmc/metrics"

In [27]:
files_0_seen = [el for el in os.listdir(data_dir) if "_0_metrics" in el]

In [29]:
dfs = []
for el in files_0_seen:
    dfs.append(pd.read_csv(os.path.join(data_dir, el), index_col=0))

In [30]:
df = pd.concat([el.T for el in dfs])
for el in df.columns:
    try:
        df[el] = df[el].astype("float")
    except:
        continue

In [31]:
df["donor_cytokine"] = df.index
df["donor"] = df.apply(lambda x: x["donor_cytokine"].split("_")[0], axis=1)
df["cytokine"] = df.apply(lambda x: x["donor_cytokine"].split("_")[1], axis=1)

/tmp/ipykernel_2299754/2027898116.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["donor_cytokine"] = df.index
/tmp/ipykernel_2299754/2027898116.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["donor"] = df.apply(lambda x: x["donor_cytokine"].split("_")[0], axis=1)
/tmp/ipykernel_2299754/2027898116.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["cytokine"] = df.apply(lambda x: x["donor_cytokine"].split("_")[1], axis=1)

In [32]:
df["cytokine"].value_counts()

cytokine
IL-15          12
4-1BBL         12
IL-13          12
OSM            12
ADSF           12
APRIL          12
Noggin         12
C5a            12
IFN-epsilon    12
BAFF           12
OX40L          12
IFN-beta       12
Name: count, dtype: int64

In [33]:
df["donor"].value_counts()

donor
Donor2     12
Donor3     12
Donor7     12
Donor10    12
Donor6     12
Donor11    12
Donor1     12
Donor12    12
Donor8     12
Donor4     12
Donor5     12
Donor9     12
Name: count, dtype: int64

In [40]:
files = os.listdir("/lustre/groups/ml01/workspace/ot_perturbation/models/otfm/pbmc_new_cytokine_stochastic_metrics")

In [42]:
len(files)

44

In [44]:
[el for el in files if "_0.1" in el]

['glowing-snowball-23_0.1.csv',
 'toic-sunset-15_0.1.csv',
 'balmy-wood-53_0.1.csv',
 'fallen-dragon-48_0.1.csv',
 'clean-capybara-39_0.1.csv',
 'worldly-glade-32_0.1.csv',
 'ight-cloud-44_0.1.csv',
 'warm-bee-26_0.1.csv',
 'celestial-shape-35_0.1.csv',
 'vital-water-12_0.1.csv',
 't-pond-20_0.1.csv']