In [2]:
import os
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [3]:
df1 = pd.read_csv("/lustre/groups/ml01/workspace/ot_perturbation/data/sciplex/results/cellflow/ood_metrics_encoded_5_direct_embedding.csv")
df2 = pd.read_csv("/lustre/groups/ml01/workspace/ot_perturbation/data/sciplex/results/cellflow/ood_metrics_encoded_5_concatenated_drug_embeddings.csv")
df3 = pd.read_csv("/lustre/groups/ml01/workspace/ot_perturbation/data/sciplex/results/cellflow/ood_metrics_encoded_5_closest_cell_line.csv")

In [6]:
model_dir = "/lustre/groups/ml01/workspace/ot_perturbation/data/sciplex/results/cellflow"
metric_files = ["ood_metrics_encoded_5_direct_embedding.csv", "ood_metrics_encoded_5_concatenated_drug_embeddings.csv", "ood_metrics_encoded_5_closest_cell_line.csv"]

In [8]:
splits = [5]
all_dfs = []
dfs = {}

for metric_file in metric_files:
    dfs[metric_file] = pd.read_csv(os.path.join(model_dir, metric_file), index_col=0)
    dfs[metric_file]["model"] = metric_file
result_df = pd.concat(dfs.values(), ignore_index=False)
result_df["metric"] = result_df.index
metrics = result_df["metric"].unique()
df2 = pd.melt(result_df, id_vars=["model", "metric"])

In [10]:
df= df2

In [11]:
df["dose"] = df.apply(lambda x: x["variable"].split("_")[-1], axis=1)

In [12]:
df_e = df[(df["metric"]=="e_distance")]

In [13]:
df_e.groupby(["model", "dose"])["value"].mean()

model                                                   dose
ood_metrics_encoded_5_closest_cell_line.csv             10.0        3.818225
                                                        100.0       6.537721
                                                        1000.0     10.029155
                                                        10000.0    30.597142
ood_metrics_encoded_5_concatenated_drug_embeddings.csv  10.0        3.645818
                                                        100.0       6.158357
                                                        1000.0      9.637669
                                                        10000.0    30.538027
ood_metrics_encoded_5_direct_embedding.csv              10.0        3.790810
                                                        100.0       6.587042
                                                        1000.0      9.837593
                                                        10000.0    30.606099
Name: value, dtype: float64

In [4]:
df1

,Unnamed: 0,A549_Alvespimycin_(17-DMAG)_HCl_10.0,A549_Alvespimycin_(17-DMAG)_HCl_100.0,A549_Belinostat_(PXD101)_10.0,A549_Belinostat_(PXD101)_100.0,A549_Belinostat_(PXD101)_1000.0,A549_Dacinostat_(LAQ824)_10.0,A549_Dacinostat_(LAQ824)_100.0,A549_Dacinostat_(LAQ824)_1000.0,A549_Flavopiridol_HCl_10.0,...,MCF7_Quisinostat_(JNJ-26481585)_2HCl_100.0,MCF7_Quisinostat_(JNJ-26481585)_2HCl_1000.0,MCF7_Quisinostat_(JNJ-26481585)_2HCl_10000.0,MCF7_TAK-901_10.0,MCF7_TAK-901_100.0,MCF7_TAK-901_1000.0,MCF7_Tanespimycin_(17-AAG)_10.0,MCF7_Tanespimycin_(17-AAG)_100.0,MCF7_Tanespimycin_(17-AAG)_1000.0,MCF7_Tanespimycin_(17-AAG)_10000.0
0,r_squared,0.989263,0.933359,0.993725,0.987504,0.879188,0.878791,0.454429,-0.563445,0.973967,...,0.014448,-0.030986,0.009981,0.972512,0.964662,0.907528,0.977002,0.799494,0.706485,0.729653
1,sinkhorn_div_1,2.362853,3.993609,2.636549,2.610492,4.915502,4.897756,10.916145,26.442984,2.657168,...,22.983162,31.217875,30.990635,1.781193,1.733419,2.366416,1.600098,2.919411,3.550172,3.315999
2,sinkhorn_div_10,0.282606,1.658541,0.220798,0.351359,2.753750,2.582515,8.228474,23.639961,0.625686,...,20.573282,28.846109,28.476334,0.214975,0.250850,0.611251,0.171272,1.296014,1.827016,1.676261
3,sinkhorn_div_100,0.223143,1.560662,0.137420,0.262576,2.642980,2.445331,7.894686,23.248749,0.555737,...,20.243343,28.506535,28.073446,0.168674,0.214119,0.539782,0.138124,1.211293,1.725213,1.587595
4,e_distance,0.437448,3.106652,0.264039,0.511728,5.265185,4.865174,15.725109,46.422863,1.100944,...,40.416750,56.942394,56.061690,0.331011,0.423933,1.070974,0.272197,2.407570,3.432819,3.159376
5,mmd,0.007081,0.029024,0.006581,0.007855,0.043390,0.038628,0.097995,0.226128,0.012626,...,0.209960,0.261243,0.257489,0.006278,0.007191,0.013656,0.005331,0.028057,0.037773,0.037942

In [2]:
df = pd.read_csv("/lustre/groups/ml01/workspace/ot_perturbation/data/sciplex/results/allocation/ood_metrics_encoded.csv")

In [3]:
df.head()

   Unnamed: 0    model        metric           variable     value  split
0           0       id     r_squared  A549_(+)-JQ1_10.0  0.993900      1
1           1       id    e_distance  A549_(+)-JQ1_10.0  0.258051      1
2           2       id           mmd  A549_(+)-JQ1_10.0  0.006600      1
3           3       id  sinkhorn_div  A549_(+)-JQ1_10.0  0.922553      1
4           4  biolord     r_squared  A549_(+)-JQ1_10.0  0.994153      1

In [12]:
df["dose"] = df.apply(lambda x: x["variable"].split("_")[-1], axis=1)

In [18]:
df_e = df[(df["metric"]=="e_distance") & (df["split"]==5)]

In [19]:
df_e.groupby(["model", "dose"])["value"].mean()

model    dose
biolord  10.0        3.722544
         100.0       6.462469
         1000.0      7.515005
         10000.0    12.213642
chemCPA  10.0        2.613913
         100.0       4.305727
         1000.0      5.616841
         10000.0    16.575733
condot   10.0        7.409134
         100.0       9.200996
         1000.0     13.091229
         10000.0    31.678298
id       10.0        3.995100
         100.0       6.895232
         1000.0     10.208338
         10000.0    33.236644
otfm     10.0        3.988151
         100.0       5.906158
         1000.0      5.822153
         10000.0     8.668549
Name: value, dtype: float64

In [23]:
df_r = df[(df["metric"]=="r_squared") & (df["split"]==5)]

In [24]:
df_r.groupby(["model", "dose"])["value"].mean()

model    dose
biolord  10.0       0.836846
         100.0      0.740680
         1000.0     0.767594
         10000.0    0.678846
chemCPA  10.0       0.888531
         100.0      0.824685
         1000.0     0.823004
         10000.0    0.589499
condot   10.0       0.723096
         100.0      0.649490
         1000.0     0.573036
         10000.0    0.252877
id       10.0       0.823207
         100.0      0.719232
         1000.0     0.681914
         10000.0    0.241639
otfm     10.0       0.817596
         100.0      0.760078
         1000.0     0.804359
         10000.0    0.748629
Name: value, dtype: float64

In [25]:
data_dir = "/lustre/groups/ml01/workspace/ot_perturbation/data/sciplex/results/otfm/pca_mean_pooling"

In [26]:
import os
os.listdir(data_dir)

['ood_metrics_encoded_15.csv',
 'ood_metrics_ood_8.csv',
 'ood_metrics_decoded_6.csv',
 'ood_metrics_ood_10.csv',
 'ood_metrics_ood_7.csv',
 'ood_metrics_decoded_9.csv',
 'ood_metrics_decoded_7.csv',
 'ood_metrics_ood_15.csv',
 'ood_metrics_decoded_8.csv',
 'ood_metrics_ood_5.csv',
 'test_metrics_deg_10.csv',
 'ood_metrics_decoded_15.csv',
 'ood_metrics_encoded_5.csv',
 'test_metrics_encoded_10.csv',
 'ood_metrics_decoded_10.csv',
 'ood_metrics_encoded_9.csv',
 'ood_metrics_encoded_7.csv',
 'ood_metrics_encoded_8.csv',
 'ood_metrics_ood_6.csv',
 'ood_metrics_encoded_6.csv',
 'test_metrics_decoded_10.csv',
 'ood_metrics_ood_9.csv',
 'ood_metrics_decoded_5.csv',
 'ood_metrics_encoded_10.csv']

In [14]:
results_decoded = pd.read_csv("/lustre/groups/ml01/workspace/ot_perturbation/data/sciplex/results/allocation/recon_cf_metrics_decoded.csv")

In [15]:
results_decoded

,Unnamed: 0,model,metric,variable,value,split,dose
0,0,otfm,r_squared,A549_Alvespimycin_(17-DMAG)_HCl_10.0,0.978079,5,10.0
1,1,recon,r_squared,A549_Alvespimycin_(17-DMAG)_HCl_10.0,0.993535,5,10.0
2,2,otfm,r_squared,A549_Alvespimycin_(17-DMAG)_HCl_100.0,0.893420,5,100.0
3,3,recon,r_squared,A549_Alvespimycin_(17-DMAG)_HCl_100.0,0.975312,5,100.0
4,4,otfm,r_squared,A549_Belinostat_(PXD101)_10.0,0.983431,5,10.0
...,...,...,...,...,...,...,...
161,161,recon,r_squared,MCF7_Tanespimycin_(17-AAG)_100.0,0.992671,5,100.0
162,162,otfm,r_squared,MCF7_Tanespimycin_(17-AAG)_1000.0,0.850750,5,1000.0
163,163,recon,r_squared,MCF7_Tanespimycin_(17-AAG)_1000.0,0.991067,5,1000.0
164,164,otfm,r_squared,MCF7_Tanespimycin_(17-AAG)_10000.0,0.856480,5,10000.0
165,165,recon,r_squared,MCF7_Tanespimycin_(17-AAG)_10000.0,0.989805,5,10000.0

In [16]:
results_decoded["dose"] = results_decoded.apply(lambda x: x["variable"].split("_")[-1], axis=1)

In [17]:
results_decoded.groupby(["model", "dose"])["value"].mean()

model  dose
otfm   10.0       0.903702
       100.0      0.863179
       1000.0     0.865927
       10000.0    0.821492
recon  10.0       0.982613
       100.0      0.977218
       1000.0     0.970973
       10000.0    0.953486
Name: value, dtype: float64

In [2]:
chemcpa_dir = "/lustre/groups/ml01/workspace/ot_perturbation/data/sciplex/results/chemcpa"
biolord_dir = "/lustre/groups/ml01/workspace/ot_perturbation/data/sciplex/results/biolord"
id_dir = "/lustre/groups/ml01/workspace/ot_perturbation/data/sciplex/results/identity"
condot_dir = "/lustre/groups/ml01/workspace/ot_perturbation/data/sciplex/results/condot"
otfm_dir = "/lustre/groups/ml01/workspace/ot_perturbation/data/sciplex/results/otfm/pca_mean_pooling"

In [3]:
model_dirs = {"id": id_dir, "biolord": biolord_dir, "otfm": otfm_dir, "condot": condot_dir, "chemCPA": chemcpa_dir}

In [4]:
splits = [1,2,3,4,5]

# Decoded

In [5]:

all_dfs = []
for split in splits:
    dfs = {}
    for model, model_dir in model_dirs.items():
        if model == "otfm":
            metrics_file = f"ood_metrics_decoded_{split+5}.csv" # because we take 100-dim PCA space for CellFlow
        else:
            metrics_file = f"ood_metrics_decoded_{split}.csv"
        dfs[model] = pd.read_csv(os.path.join(model_dir, metrics_file), index_col=0)
        #dfs[model].loc["sinkhorn_div"] = dfs[model].loc[["sinkhorn_div_1", "sinkhorn_div_10", "sinkhorn_div_100"]].mean(axis=0)
        if "sinkhorn_div_1" in dfs[model].index:
            dfs[model] = dfs[model].drop(["sinkhorn_div_1", "sinkhorn_div_10", "sinkhorn_div_100"])
        if "mmd_distance" in dfs[model].index:
            dfs[model] = dfs[model].drop(["mmd_distance"])
        if "mmd" in dfs[model].index:
            dfs[model] = dfs[model].drop(["mmd"])
        if "e_distance" in dfs[model].index:
            dfs[model] = dfs[model].drop(["e_distance"])
        dfs[model]["model"] = model
    result_df = pd.concat(dfs.values(), ignore_index=False)
    result_df["metric"] = result_df.index
    metrics = result_df["metric"].unique()
    df2 = pd.melt(result_df, id_vars=["model", "metric"])
    df2["split"] = split
    all_dfs.append(df2)

In [6]:
df_ood_metrics_decoded = pd.concat(all_dfs)

In [7]:
df_ood_metrics_decoded

       model     metric                            variable     value  split
0         id  r_squared                   A549_(+)-JQ1_10.0  0.988324      1
1    biolord  r_squared                   A549_(+)-JQ1_10.0  0.989759      1
2       otfm  r_squared                   A549_(+)-JQ1_10.0  0.988828      1
3     condot  r_squared                   A549_(+)-JQ1_10.0  0.701462      1
4    chemCPA  r_squared                   A549_(+)-JQ1_10.0  0.993324      1
..       ...        ...                                 ...       ...    ...
410       id  r_squared  MCF7_Tanespimycin_(17-AAG)_10000.0  0.869440      5
411  biolord  r_squared  MCF7_Tanespimycin_(17-AAG)_10000.0  0.883039      5
412     otfm  r_squared  MCF7_Tanespimycin_(17-AAG)_10000.0  0.856480      5
413   condot  r_squared  MCF7_Tanespimycin_(17-AAG)_10000.0  0.770208      5
414  chemCPA  r_squared  MCF7_Tanespimycin_(17-AAG)_10000.0  0.923188      5

[11040 rows x 5 columns]

In [8]:
df_ood_metrics_decoded.to_csv("/lustre/groups/ml01/workspace/ot_perturbation/data/sciplex/results/allocation/ood_metrics_decoded.csv")

In [9]:

all_dfs = []
for split in splits:
    dfs = {}
    for model, model_dir in model_dirs.items():
        if model == "otfm": 
            metrics_file = f"ood_metrics_encoded_{split+5}.csv" # because we take 100-dim PCA space for CellFlow
        else:
            metrics_file = f"ood_metrics_encoded_{split}.csv"
        dfs[model] = pd.read_csv(os.path.join(model_dir, metrics_file), index_col=0)
        dfs[model].loc["sinkhorn_div"] = dfs[model].loc[["sinkhorn_div_1", "sinkhorn_div_10", "sinkhorn_div_100"]].mean(axis=0)
        dfs[model] = dfs[model].drop(["sinkhorn_div_1", "sinkhorn_div_10", "sinkhorn_div_100"])
        dfs[model]["model"] = model
    result_df = pd.concat(dfs.values(), ignore_index=False)
    result_df["metric"] = result_df.index
    metrics = result_df["metric"].unique()
    df2 = pd.melt(result_df, id_vars=["model", "metric"])
    df2["split"] = split
    all_dfs.append(df2)

In [10]:
df_ood_metrics_encoded = pd.concat(all_dfs)

In [11]:
df_ood_metrics_encoded["metric"].value_counts()

metric
r_squared       11040
e_distance      11040
mmd             11040
sinkhorn_div    11040
Name: count, dtype: int64

In [12]:
df_ood_metrics_encoded.to_csv("/lustre/groups/ml01/workspace/ot_perturbation/data/sciplex/results/allocation/ood_metrics_encoded.csv")

In [13]:

all_dfs = []
for split in splits:
    dfs = {}
    for model, model_dir in model_dirs.items():
        if model == "otfm": 
            metrics_file = f"ood_metrics_encoded_{split+5}.csv" # because we take 100-dim PCA space for CellFlow
        else:
            metrics_file = f"ood_metrics_encoded_{split}.csv"
        dfs[model] = pd.read_csv(os.path.join(model_dir, metrics_file), index_col=0)
        dfs[model].loc["sinkhorn_div"] = dfs[model].loc[["sinkhorn_div_1", "sinkhorn_div_10", "sinkhorn_div_100"]].mean(axis=0)
        dfs[model] = dfs[model].drop(["sinkhorn_div_1", "sinkhorn_div_10", "sinkhorn_div_100"])
        dfs[model]["model"] = model
    result_df = pd.concat(dfs.values(), ignore_index=False)
    result_df["metric"] = result_df.index
    metrics = result_df["metric"].unique()
    df2 = pd.melt(result_df, id_vars=["model", "metric"])
    df2["split"] = split
    all_dfs.append(df2)

In [14]:
df_ood_metrics_deg = pd.concat(all_dfs)

In [15]:
df_ood_metrics_deg

,model,metric,variable,value,split
0,id,r_squared,A549_(+)-JQ1_10.0,0.993900,1
1,id,e_distance,A549_(+)-JQ1_10.0,0.258051,1
2,id,mmd,A549_(+)-JQ1_10.0,0.006600,1
3,id,sinkhorn_div,A549_(+)-JQ1_10.0,0.922553,1
4,biolord,r_squared,A549_(+)-JQ1_10.0,0.994153,1
...,...,...,...,...,...
1655,condot,sinkhorn_div,MCF7_Tanespimycin_(17-AAG)_10000.0,6.530088,5
1656,chemCPA,r_squared,MCF7_Tanespimycin_(17-AAG)_10000.0,0.807001,5
1657,chemCPA,e_distance,MCF7_Tanespimycin_(17-AAG)_10000.0,2.179901,5
1658,chemCPA,mmd,MCF7_Tanespimycin_(17-AAG)_10000.0,0.298021,5
1659,chemCPA,sinkhorn_div,MCF7_Tanespimycin_(17-AAG)_10000.0,1.780267,5

In [16]:
df_ood_metrics_deg.to_csv("/lustre/groups/ml01/workspace/ot_perturbation/data/sciplex/results/allocation/ood_metrics_deg.csv")