In [1]:
import os
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [2]:
chemcpa_dir = "/lustre/groups/ml01/workspace/ot_perturbation/data/sciplex/results/chemcpa"
biolord_dir = "/lustre/groups/ml01/workspace/ot_perturbation/data/sciplex/results/biolord"
id_dir = "/lustre/groups/ml01/workspace/ot_perturbation/data/sciplex/results/identity"
condot_dir = "/lustre/groups/ml01/workspace/ot_perturbation/data/sciplex/results/condot"
cl_dir = "/lustre/groups/ml01/workspace/ot_perturbation/data/sciplex/results/closest_embedding"
otfm_dir = "/lustre/groups/ml01/workspace/ot_perturbation/data/sciplex/results/otfm/pca_mean_pooling"

In [3]:
model_dirs = {"id": id_dir, "biolord": biolord_dir, "otfm": otfm_dir, "condot": condot_dir, "chemCPA": chemcpa_dir, "cl": cl_dir}

In [4]:
splits = [5]

In [5]:
df_id = pd.read_csv(os.path.join(id_dir, "ood_metrics_encoded_5.csv"), index_col=0)
df_cl = pd.read_csv(os.path.join(cl_dir, "ood_metrics_encoded_5.csv"), index_col=0)

In [6]:
df_id

,A549_Alvespimycin_(17-DMAG)_HCl_10.0,A549_Alvespimycin_(17-DMAG)_HCl_100.0,A549_Belinostat_(PXD101)_10.0,A549_Belinostat_(PXD101)_100.0,A549_Belinostat_(PXD101)_1000.0,A549_Dacinostat_(LAQ824)_10.0,A549_Dacinostat_(LAQ824)_100.0,A549_Dacinostat_(LAQ824)_1000.0,A549_Flavopiridol_HCl_10.0,A549_Flavopiridol_HCl_100.0,...,MCF7_Quisinostat_(JNJ-26481585)_2HCl_100.0,MCF7_Quisinostat_(JNJ-26481585)_2HCl_1000.0,MCF7_Quisinostat_(JNJ-26481585)_2HCl_10000.0,MCF7_TAK-901_10.0,MCF7_TAK-901_100.0,MCF7_TAK-901_1000.0,MCF7_Tanespimycin_(17-AAG)_10.0,MCF7_Tanespimycin_(17-AAG)_100.0,MCF7_Tanespimycin_(17-AAG)_1000.0,MCF7_Tanespimycin_(17-AAG)_10000.0
r_squared,0.991957,0.927052,0.989759,0.981975,0.866370,0.869501,0.427423,-0.603800,0.977870,0.728241,...,-0.016266,-0.048846,-0.072117,0.958611,0.953261,0.912535,0.972290,0.779775,0.690923,0.662353
sinkhorn_div_1,2.307025,4.128780,2.716664,2.714895,5.193576,5.085152,11.299255,27.051903,2.573650,6.816446,...,23.613262,31.708105,33.317558,1.860462,1.795921,2.333364,1.623790,3.031616,3.635315,3.704210
sinkhorn_div_10,0.227769,1.803228,0.303897,0.463155,3.033432,2.769406,8.616455,24.241169,0.543386,4.491053,...,21.203529,29.338650,30.801771,0.298410,0.319118,0.582773,0.199063,1.414109,1.917632,2.069400
sinkhorn_div_100,0.168244,1.707416,0.220857,0.375640,2.922339,2.631795,8.283750,23.847782,0.473164,4.287161,...,20.873260,28.999487,30.398010,0.252384,0.282484,0.510885,0.165966,1.329693,1.816133,1.980951
e_distance,0.327692,3.400646,0.430965,0.738167,5.823819,5.238036,16.503496,47.621104,0.935901,8.531695,...,41.676289,57.928829,60.710620,0.498419,0.560711,1.012994,0.327969,2.644340,3.614822,3.945865
mmd,0.006430,0.031141,0.007781,0.009462,0.046849,0.041040,0.101762,0.229107,0.011590,0.056519,...,0.213791,0.263644,0.268079,0.007557,0.008315,0.013167,0.005725,0.029571,0.038917,0.043850

In [7]:
df_cl

,A549_Alvespimycin_(17-DMAG)_HCl_10.0,A549_Alvespimycin_(17-DMAG)_HCl_100.0,A549_Belinostat_(PXD101)_10.0,A549_Belinostat_(PXD101)_100.0,A549_Belinostat_(PXD101)_1000.0,A549_Dacinostat_(LAQ824)_10.0,A549_Dacinostat_(LAQ824)_100.0,A549_Dacinostat_(LAQ824)_1000.0,A549_Flavopiridol_HCl_10.0,A549_Flavopiridol_HCl_100.0,...,MCF7_Quisinostat_(JNJ-26481585)_2HCl_100.0,MCF7_Quisinostat_(JNJ-26481585)_2HCl_1000.0,MCF7_Quisinostat_(JNJ-26481585)_2HCl_10000.0,MCF7_TAK-901_10.0,MCF7_TAK-901_100.0,MCF7_TAK-901_1000.0,MCF7_Tanespimycin_(17-AAG)_10.0,MCF7_Tanespimycin_(17-AAG)_100.0,MCF7_Tanespimycin_(17-AAG)_1000.0,MCF7_Tanespimycin_(17-AAG)_10000.0
r_squared,-0.081489,-0.078285,-0.087396,-0.089256,-0.069852,-0.072992,-0.013817,0.056684,-0.078547,-0.058458,...,0.137595,0.108522,0.098885,0.223588,0.231106,0.236402,0.235740,0.234715,0.230739,0.223331
e_distance,44.060265,50.267020,45.758003,44.606530,46.625748,43.068375,29.221443,28.009567,45.612810,33.229560,...,35.366570,49.237236,51.027320,9.349739,9.224094,8.843742,9.045578,9.189110,8.996941,9.076450
mmd,0.142243,0.161163,0.136622,0.137607,0.157021,0.147192,0.130940,0.160808,0.147837,0.131581,...,0.155750,0.192898,0.195410,0.039076,0.040463,0.041804,0.039931,0.053745,0.056998,0.062735

# Decoded

In [8]:

all_dfs = []
for split in splits:
    dfs = {}
    for model, model_dir in model_dirs.items():
        if model == "otfm":
            metrics_file = f"ood_metrics_decoded_{split+5}.csv" # because we take 100-dim PCA space for CellFlow
        else:
            metrics_file = f"ood_metrics_decoded_{split}.csv"
        dfs[model] = pd.read_csv(os.path.join(model_dir, metrics_file), index_col=0)
        #dfs[model].loc["sinkhorn_div"] = dfs[model].loc[["sinkhorn_div_1", "sinkhorn_div_10", "sinkhorn_div_100"]].mean(axis=0)
        if "sinkhorn_div_1" in dfs[model].index:
            dfs[model] = dfs[model].drop(["sinkhorn_div_1", "sinkhorn_div_10", "sinkhorn_div_100"])
        if "mmd_distance" in dfs[model].index:
            dfs[model] = dfs[model].drop(["mmd_distance"])
        if "mmd" in dfs[model].index:
            dfs[model] = dfs[model].drop(["mmd"])
        if "e_distance" in dfs[model].index:
            dfs[model] = dfs[model].drop(["e_distance"])
        dfs[model]["model"] = model
    result_df = pd.concat(dfs.values(), ignore_index=False)
    result_df["metric"] = result_df.index
    metrics = result_df["metric"].unique()
    df2 = pd.melt(result_df, id_vars=["model", "metric"])
    df2["split"] = split
    all_dfs.append(df2)

In [9]:
df_ood_metrics_decoded = pd.concat(all_dfs)

In [10]:
df_ood_metrics_decoded.to_csv("/lustre/groups/ml01/workspace/ot_perturbation/data/sciplex/results/allocation/ood_metrics_decoded.csv")

In [11]:

all_dfs = []
for split in splits:
    dfs = {}
    for model, model_dir in model_dirs.items():
        if model == "otfm": 
            metrics_file = f"ood_metrics_encoded_{split+5}.csv" # because we take 100-dim PCA space for CellFlow
        else:
            metrics_file = f"ood_metrics_encoded_{split}.csv"
        
        dfs[model] = pd.read_csv(os.path.join(model_dir, metrics_file), index_col=0)
        if "sinkhorn_div_1" in dfs[model].index:
            dfs[model] = dfs[model].drop(["sinkhorn_div_1", "sinkhorn_div_10", "sinkhorn_div_100"])
        dfs[model]["model"] = model
    result_df = pd.concat(dfs.values(), ignore_index=False)
    result_df["metric"] = result_df.index
    metrics = result_df["metric"].unique()
    df2 = pd.melt(result_df, id_vars=["model", "metric"])
    df2["split"] = split
    all_dfs.append(df2)

In [12]:
df_ood_metrics_encoded = pd.concat(all_dfs)

In [13]:
df_ood_metrics_encoded["metric"].value_counts()

metric
r_squared     498
e_distance    498
mmd           498
Name: count, dtype: int64

In [14]:
df_ood_metrics_encoded.to_csv("/lustre/groups/ml01/workspace/ot_perturbation/data/sciplex/results/allocation/ood_metrics_encoded.csv")

In [15]:

all_dfs = []
for split in splits:
    dfs = {}
    for model, model_dir in model_dirs.items():
        if model == "otfm": 
            metrics_file = f"ood_metrics_encoded_{split+5}.csv" # because we take 100-dim PCA space for CellFlow
        else:
            metrics_file = f"ood_metrics_encoded_{split}.csv"
        dfs[model] = pd.read_csv(os.path.join(model_dir, metrics_file), index_col=0)
        if "sinkhorn_div_1" in dfs[model].index:
            dfs[model] = dfs[model].drop(["sinkhorn_div_1", "sinkhorn_div_10", "sinkhorn_div_100"])
        dfs[model]["model"] = model
    result_df = pd.concat(dfs.values(), ignore_index=False)
    result_df["metric"] = result_df.index
    metrics = result_df["metric"].unique()
    df2 = pd.melt(result_df, id_vars=["model", "metric"])
    df2["split"] = split
    all_dfs.append(df2)

In [16]:
df_ood_metrics_deg = pd.concat(all_dfs)

In [17]:
df_ood_metrics_deg.to_csv("/lustre/groups/ml01/workspace/ot_perturbation/data/sciplex/results/allocation/ood_metrics_deg.csv")